### ISSUE TITLE
Invalid property value

### ISSUE THREAD

**Issue by DavithkbY** [cositehq/sanity-plugin-simpler-color-input#11] opened 2024-06-18 07:30 UTC
When setting the color via react, I get 'invalid property value' in my css and the color is not being set.

Code:

<img width="715" alt="image" src="https://github.com/cositehq/sanity-plugin-simpler-color-input/assets/71630103/7461972a-ecf3-4c04-992c-61732ea140ba">
<img width="210" alt="image" src="https://github.com/cositehq/sanity-plugin-simpler-color-input/assets/71630103/ec90193d-218a-42a0-922b-848e6d8fe20c">
<img width="1356" alt="image" src="https://github.com/cositehq/sanity-plugin-simpler-color-input/assets/71630103/661d0f02-71bf-45db-a946-5c5b54547877">

**Comment by krokosik** [comment] 2024-07-21 13:15
I have the same issue with HEX values.

**Comment by krokosik** [comment] 2024-07-21 13:34
I've tested this on 2.2.1 and 2.2.2 versions. Found a temporary solution using `trim()`
```typescript
textColor: ({
  children,
  value,
}: PortableTextMarkComponentProps) => (
  <span
    style={{ color: (value?.value as string | undefined)?.trim() }}
  >
    {children}
  </span>
),
highlightColor: ({
  children,
  value,
}: PortableTextMarkComponentProps) => (
  <span
    style={{
      backgroundColor: (value?.value as string | undefined)?.trim(),
    }}
  >
    {children}
  </span>
),
```

The content still has these trash whitespaces. Don't know how to fix that, since I've never dealt with Sanity internals.

**Comment by krokosik** [comment] 2024-07-21 22:38
Okay this actually needs adding for ALL usages of color values, making this plugin practically unusable as of now :/

**Comment by AlyssaKirstine** [comment] 2024-07-25 15:21
@krokosik Hmm feel free to put up a fix for this if you know how to otherwise I will try to take a look at/fix this soon.

**Comment by krokosik** [comment] 2024-07-27 18:09
I took a brief look through the code, but could not find the cause. I only have the dirty workaround in my code.

**Comment by AlyssaKirstine** [comment] 2024-09-10 18:54
Hi @DavithkbY and @krokosik, I got a chance to look into this and it looks like it's caused from using visual editing in the Sanity studio and having Stega-encoding enabled. You can read the documentation [here](https://www.sanity.io/docs/stega) about this. If you scroll to the bottom of the page, they have a function called `stegaClean` that you can use to clean the value before using it.

Unfortunately, this isn't something I can do in the plugin itself since the frontend adds in these whitespace characters after receiving the query data.

So @krokosik you could update your code to the following to use this function:
```
import {stegaClean} from '@sanity/client/stega'

textColor: ({
  children,
  value,
}: PortableTextMarkComponentProps) => (
  <span
    style={{ color: stegaClean(value?.value) }}
  >
    {children}
  </span>
),
highlightColor: ({
  children,
  value,
}: PortableTextMarkComponentProps) => (
  <span
    style={{
      backgroundColor: stegaClean(value?.value)
    }}
  >
    {children}
  </span>
),
```

I'm going to close this issue, but feel free to reach out if you need anything else.

**Closed by AlyssaKirstine** 2024-09-10 18:54 UTC

**Comment by AlyssaKirstine** [comment] 2024-09-10 19:28
Adding on as well that you can alternatively filter these out when you initialize the Sanity client rather than cleaning them in each instance they're used in.

Here's the code for how to do this:
```
export default createClient({
	projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
	dataset: process.env.NEXT_PUBLIC_SANITY_DATASET,
	apiVersion: '2024-07-01',
	stega: {
		enabled: true,
		studioUrl: '/admin',
		filter: (props) => {
			if (props.sourcePath.includes('backgroundColor')) return false // filter out simpler color input field
			if (props.sourcePath.includes('content')) return false // filter out portable text field

			return props.filterDefault(props)
		},
	},
})
```

You would replace `backgroundColor` and `content` with the name of the field that uses the simpler color type. For portable text, this needs to be the whole block itself, so whichever field has `type: 'block'`. For a regular simpler color input field, you would just use the name of that.

When Sanity sees this, they won't add stega-encoding to these fields. There could of course be other drawbacks to doing this, but I thought I'd call out this alternative solution as well!

**Comment by krokosik** [comment] 2024-09-27 08:29
Thank you @AlyssaKirstine for looking into this! I really enjoy using this plugin.
